version: "3.8"

services:
  meteorapp:
    build:
      context: . # Replace with the path to your Meteor app's source code
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # Change the host port if you need to map to a different port
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/inventory-app?&authSource=admin
      PORT: 3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4
    restart: always
    volumes:
      - inventory_app_mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "${MONGO_ADMIN_PORT}:8081"
    depends_on:
      - mongodb

volumes:
  inventory_app_mongodb_data:
    driver: local
